# Generated by Django 3.1.3 on 2020-11-30 02:14

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Users',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128)),
                ('last_login', models.CharField(max_length=200)),
                ('is_superuser', models.SmallIntegerField()),
                ('username', models.CharField(max_length=150, unique=True)),
                ('first_name', models.CharField(max_length=150)),
                ('last_name', models.CharField(max_length=150)),
                ('email', models.CharField(max_length=254)),
                ('is_staff', models.SmallIntegerField()),
                ('is_active', models.SmallIntegerField()),
                ('date_joined', models.CharField(max_length=200)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Conversions',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_id', models.CharField(max_length=10)),
                ('from_id', models.CharField(max_length=10)),
                ('to_id', models.CharField(max_length=10)),
                ('rate', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Currencies',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=254)),
                ('user_id', models.CharField(max_length=254)),
                ('shortname', models.CharField(max_length=10)),
                ('is_active', models.CharField(max_length=200)),
                ('updated_at', models.CharField(max_length=200)),
                ('created_at', models.CharField(max_length=200)),
            ],
        ),
    ]
